In [1]:
import pandas as pd

In [3]:
pd.set_option('display.max_row',10) #set_optionを使用すると一回一回定義しなくてもいい

In [6]:
df_csv = pd.read_csv('data.csv',encoding = 'shift-jis')
df_csv

,都道府県,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),...,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
0,全国,"55,963","59,737","64,450","69,254","71,933","78,101","84,115","90,077","94,302",...,"104,665","111,940","117,060","121,049","123,611","125,570","126,926","127,768","128,057","127,095"
1,北海道,"2,359","2,499","2,812","3,068","3,229","3,853","4,296","4,773","5,039",...,"5,184","5,338","5,576","5,679","5,644","5,692","5,683","5,628","5,506","5,382"
2,青森,756,813,880,967,985,"1,180","1,283","1,383","1,427",...,"1,428","1,469","1,524","1,524","1,483","1,482","1,476","1,437","1,373","1,308"
3,岩手,846,901,976,"1,046","1,078","1,263","1,347","1,427","1,449",...,"1,371","1,386","1,422","1,434","1,417","1,420","1,416","1,385","1,330","1,280"
4,宮城,962,"1,044","1,143","1,235","1,247","1,567","1,663","1,727","1,743",...,"1,819","1,955","2,082","2,176","2,249","2,329","2,365","2,360","2,348","2,334"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,熊本,"1,233","1,296","1,354","1,387","1,338","1,766","1,828","1,896","1,856",...,"1,700","1,715","1,790","1,838","1,840","1,860","1,859","1,842","1,817","1,786"
44,大分,860,915,946,980,953,"1,234","1,253","1,277","1,240",...,"1,156","1,190","1,229","1,250","1,237","1,231","1,221","1,210","1,197","1,166"
45,宮崎,651,691,760,824,823,"1,026","1,091","1,139","1,135",...,"1,051","1,085","1,152","1,176","1,169","1,176","1,170","1,153","1,135","1,104"
46,鹿児島,"1,416","1,472","1,557","1,591","1,554","1,746","1,804","2,044","1,963",...,"1,729","1,724","1,785","1,819","1,798","1,794","1,786","1,753","1,706","1,648"
47,沖縄,572,558,578,592,566,…,915,801,883,...,945,"1,043","1,107","1,179","1,222","1,273","1,318","1,362","1,393","1,434"

In [9]:
df_csv = pd.read_csv('data01.csv',encoding = 'shift-jis', names = ['area_code','area','GG','gg','yyyy','population','man','woman'])
df_csv

,,,,,,,,,,,,,area_code,area,GG,gg,yyyy,population,man,woman
北海道,"2,359","2,499","2,812","3,068","3,229","3,853","4,296","4,773","5,039","5,172","5,184","5,338","5,576","5,679","5,644","5,692","5,683","5,628","5,506","5,382"
青森,756,813,880,967,985,"1,180","1,283","1,383","1,427","1,417","1,428","1,469","1,524","1,524","1,483","1,482","1,476","1,437","1,373","1,308"
岩手,846,901,976,"1,046","1,078","1,263","1,347","1,427","1,449","1,411","1,371","1,386","1,422","1,434","1,417","1,420","1,416","1,385","1,330","1,280"
宮城,962,"1,044","1,143","1,235","1,247","1,567","1,663","1,727","1,743","1,753","1,819","1,955","2,082","2,176","2,249","2,329","2,365","2,360","2,348","2,334"
秋田,899,936,988,"1,038","1,035","1,257","1,309","1,349","1,336","1,280","1,241","1,232","1,257","1,254","1,227","1,214","1,189","1,146","1,086","1,023"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
熊本,"1,233","1,296","1,354","1,387","1,338","1,766","1,828","1,896","1,856","1,771","1,700","1,715","1,790","1,838","1,840","1,860","1,859","1,842","1,817","1,786"
大分,860,915,946,980,953,"1,234","1,253","1,277","1,240","1,187","1,156","1,190","1,229","1,250","1,237","1,231","1,221","1,210","1,197","1,166"
宮崎,651,691,760,824,823,"1,026","1,091","1,139","1,135","1,081","1,051","1,085","1,152","1,176","1,169","1,176","1,170","1,153","1,135","1,104"
鹿児島,"1,416","1,472","1,557","1,591","1,554","1,746","1,804","2,044","1,963","1,854","1,729","1,724","1,785","1,819","1,798","1,794","1,786","1,753","1,706","1,648"
沖縄,572,558,578,592,566,…,915,801,883,934,945,"1,043","1,107","1,179","1,222","1,273","1,318","1,362","1,393","1,434"

In [11]:
df_csv = pd.read_csv('data.csv' , encoding = 'shift-jis' , index_col = [0])
#指定した列をインデックスにする。index_col
df_csv

,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),1965年,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
都道府県,,,,,,,,,,,,,,,,,,,,
全国,"55,963","59,737","64,450","69,254","71,933","78,101","84,115","90,077","94,302","99,209","104,665","111,940","117,060","121,049","123,611","125,570","126,926","127,768","128,057","127,095"
北海道,"2,359","2,499","2,812","3,068","3,229","3,853","4,296","4,773","5,039","5,172","5,184","5,338","5,576","5,679","5,644","5,692","5,683","5,628","5,506","5,382"
青森,756,813,880,967,985,"1,180","1,283","1,383","1,427","1,417","1,428","1,469","1,524","1,524","1,483","1,482","1,476","1,437","1,373","1,308"
岩手,846,901,976,"1,046","1,078","1,263","1,347","1,427","1,449","1,411","1,371","1,386","1,422","1,434","1,417","1,420","1,416","1,385","1,330","1,280"
宮城,962,"1,044","1,143","1,235","1,247","1,567","1,663","1,727","1,743","1,753","1,819","1,955","2,082","2,176","2,249","2,329","2,365","2,360","2,348","2,334"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
熊本,"1,233","1,296","1,354","1,387","1,338","1,766","1,828","1,896","1,856","1,771","1,700","1,715","1,790","1,838","1,840","1,860","1,859","1,842","1,817","1,786"
大分,860,915,946,980,953,"1,234","1,253","1,277","1,240","1,187","1,156","1,190","1,229","1,250","1,237","1,231","1,221","1,210","1,197","1,166"
宮崎,651,691,760,824,823,"1,026","1,091","1,139","1,135","1,081","1,051","1,085","1,152","1,176","1,169","1,176","1,170","1,153","1,135","1,104"
鹿児島,"1,416","1,472","1,557","1,591","1,554","1,746","1,804","2,044","1,963","1,854","1,729","1,724","1,785","1,819","1,798","1,794","1,786","1,753","1,706","1,648"
沖縄,572,558,578,592,566,…,915,801,883,934,945,"1,043","1,107","1,179","1,222","1,273","1,318","1,362","1,393","1,434"

In [12]:
df_csv = pd.read_csv('data.csv',encoding='shift-jis',index_col=[0,1,2])
df_csv

,,,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),1965年,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
都道府県,1920年,1925年,,,,,,,,,,,,,,,,,,
全国,"55,963","59,737","64,450","69,254","71,933","78,101","84,115","90,077","94,302","99,209","104,665","111,940","117,060","121,049","123,611","125,570","126,926","127,768","128,057","127,095"
北海道,"2,359","2,499","2,812","3,068","3,229","3,853","4,296","4,773","5,039","5,172","5,184","5,338","5,576","5,679","5,644","5,692","5,683","5,628","5,506","5,382"
青森,756,813,880,967,985,"1,180","1,283","1,383","1,427","1,417","1,428","1,469","1,524","1,524","1,483","1,482","1,476","1,437","1,373","1,308"
岩手,846,901,976,"1,046","1,078","1,263","1,347","1,427","1,449","1,411","1,371","1,386","1,422","1,434","1,417","1,420","1,416","1,385","1,330","1,280"
宮城,962,"1,044","1,143","1,235","1,247","1,567","1,663","1,727","1,743","1,753","1,819","1,955","2,082","2,176","2,249","2,329","2,365","2,360","2,348","2,334"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
熊本,"1,233","1,296","1,354","1,387","1,338","1,766","1,828","1,896","1,856","1,771","1,700","1,715","1,790","1,838","1,840","1,860","1,859","1,842","1,817","1,786"
大分,860,915,946,980,953,"1,234","1,253","1,277","1,240","1,187","1,156","1,190","1,229","1,250","1,237","1,231","1,221","1,210","1,197","1,166"
宮崎,651,691,760,824,823,"1,026","1,091","1,139","1,135","1,081","1,051","1,085","1,152","1,176","1,169","1,176","1,170","1,153","1,135","1,104"
鹿児島,"1,416","1,472","1,557","1,591","1,554","1,746","1,804","2,044","1,963","1,854","1,729","1,724","1,785","1,819","1,798","1,794","1,786","1,753","1,706","1,648"
沖縄,572,558,578,592,566,…,915,801,883,934,945,"1,043","1,107","1,179","1,222","1,273","1,318","1,362","1,393","1,434"

In [13]:
df_csv.dtypes

1930年      object
1935年      object
1940年1)    object
1947年2)    object
1950年      object
            ...
1995年      object
2000年      object
2005年      object
2010年      object
2015年      object
Length: 18, dtype: object

In [14]:
type(df_csv.index)

pandas.core.indexes.multi.MultiIndex

In [15]:
#データフレームをcsvファイルに書き出す方法to_csv

In [16]:
df_csv.to_csv('data_csv.csv',encoding = 'shift-jis')

In [17]:
#文字コードを指定するのは、文字化けしないようにするため

In [18]:
#Excelデータの読み込み方法

In [19]:
pd.read_excel('data.xlsx')

,都道府県,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),...,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
0,全国,55963,59737,64450,69254,71933,78101,84115,90077,94302,...,104665,111940,117060,121049,123611,125570,126926,127768,128057,127095
1,北海道,2359,2499,2812,3068,3229,3853,4296,4773,5039,...,5184,5338,5576,5679,5644,5692,5683,5628,5506,5382
2,青森,756,813,880,967,985,1180,1283,1383,1427,...,1428,1469,1524,1524,1483,1482,1476,1437,1373,1308
3,岩手,846,901,976,1046,1078,1263,1347,1427,1449,...,1371,1386,1422,1434,1417,1420,1416,1385,1330,1280
4,宮城,962,1044,1143,1235,1247,1567,1663,1727,1743,...,1819,1955,2082,2176,2249,2329,2365,2360,2348,2334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,熊本,1233,1296,1354,1387,1338,1766,1828,1896,1856,...,1700,1715,1790,1838,1840,1860,1859,1842,1817,1786
44,大分,860,915,946,980,953,1234,1253,1277,1240,...,1156,1190,1229,1250,1237,1231,1221,1210,1197,1166
45,宮崎,651,691,760,824,823,1026,1091,1139,1135,...,1051,1085,1152,1176,1169,1176,1170,1153,1135,1104
46,鹿児島,1416,1472,1557,1591,1554,1746,1804,2044,1963,...,1729,1724,1785,1819,1798,1794,1786,1753,1706,1648
47,沖縄,572,558,578,592,566,…,915,801,883,...,945,1043,1107,1179,1222,1273,1318,1362,1393,1434

In [21]:
pd.read_excel('data01.xlsx')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,都道府県,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),...,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
2,全国,55963,59737,64450,69254,71933,78101,84115,90077,94302,...,104665,111940,117060,121049,123611,125570,126926,127768,128057,127095
3,北海道,2359,2499,2812,3068,3229,3853,4296,4773,5039,...,5184,5338,5576,5679,5644,5692,5683,5628,5506,5382
4,青森,756,813,880,967,985,1180,1283,1383,1427,...,1428,1469,1524,1524,1483,1482,1476,1437,1373,1308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,熊本,1233,1296,1354,1387,1338,1766,1828,1896,1856,...,1700,1715,1790,1838,1840,1860,1859,1842,1817,1786
46,大分,860,915,946,980,953,1234,1253,1277,1240,...,1156,1190,1229,1250,1237,1231,1221,1210,1197,1166
47,宮崎,651,691,760,824,823,1026,1091,1139,1135,...,1051,1085,1152,1176,1169,1176,1170,1153,1135,1104
48,鹿児島,1416,1472,1557,1591,1554,1746,1804,2044,1963,...,1729,1724,1785,1819,1798,1794,1786,1753,1706,1648
49,沖縄,572,558,578,592,566,…,915,801,883,...,945,1043,1107,1179,1222,1273,1318,1362,1393,1434

In [22]:
pd.read_excel('data01.xlsx',skiprows = 2) #上の２行の空白をスキップすることができるskiprows

,都道府県,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),...,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
0,全国,55963,59737,64450,69254,71933,78101,84115,90077,94302,...,104665,111940,117060,121049,123611,125570,126926,127768,128057,127095
1,北海道,2359,2499,2812,3068,3229,3853,4296,4773,5039,...,5184,5338,5576,5679,5644,5692,5683,5628,5506,5382
2,青森,756,813,880,967,985,1180,1283,1383,1427,...,1428,1469,1524,1524,1483,1482,1476,1437,1373,1308
3,岩手,846,901,976,1046,1078,1263,1347,1427,1449,...,1371,1386,1422,1434,1417,1420,1416,1385,1330,1280
4,宮城,962,1044,1143,1235,1247,1567,1663,1727,1743,...,1819,1955,2082,2176,2249,2329,2365,2360,2348,2334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,熊本,1233,1296,1354,1387,1338,1766,1828,1896,1856,...,1700,1715,1790,1838,1840,1860,1859,1842,1817,1786
44,大分,860,915,946,980,953,1234,1253,1277,1240,...,1156,1190,1229,1250,1237,1231,1221,1210,1197,1166
45,宮崎,651,691,760,824,823,1026,1091,1139,1135,...,1051,1085,1152,1176,1169,1176,1170,1153,1135,1104
46,鹿児島,1416,1472,1557,1591,1554,1746,1804,2044,1963,...,1729,1724,1785,1819,1798,1794,1786,1753,1706,1648
47,沖縄,572,558,578,592,566,…,915,801,883,...,945,1043,1107,1179,1222,1273,1318,1362,1393,1434

In [23]:
pd.read_excel('data01.xlsx',skiprows = 2,header = [1]) #上の２行の空白をスキップすることができるskiprows

,全国,55963,59737,64450,69254,71933,78101,84115,90077,94302,...,104665,111940,117060,121049,123611,125570,126926,127768,128057,127095
0,北海道,2359,2499,2812,3068,3229,3853,4296,4773,5039,...,5184,5338,5576,5679,5644,5692,5683,5628,5506,5382
1,青森,756,813,880,967,985,1180,1283,1383,1427,...,1428,1469,1524,1524,1483,1482,1476,1437,1373,1308
2,岩手,846,901,976,1046,1078,1263,1347,1427,1449,...,1371,1386,1422,1434,1417,1420,1416,1385,1330,1280
3,宮城,962,1044,1143,1235,1247,1567,1663,1727,1743,...,1819,1955,2082,2176,2249,2329,2365,2360,2348,2334
4,秋田,899,936,988,1038,1035,1257,1309,1349,1336,...,1241,1232,1257,1254,1227,1214,1189,1146,1086,1023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,熊本,1233,1296,1354,1387,1338,1766,1828,1896,1856,...,1700,1715,1790,1838,1840,1860,1859,1842,1817,1786
43,大分,860,915,946,980,953,1234,1253,1277,1240,...,1156,1190,1229,1250,1237,1231,1221,1210,1197,1166
44,宮崎,651,691,760,824,823,1026,1091,1139,1135,...,1051,1085,1152,1176,1169,1176,1170,1153,1135,1104
45,鹿児島,1416,1472,1557,1591,1554,1746,1804,2044,1963,...,1729,1724,1785,1819,1798,1794,1786,1753,1706,1648
46,沖縄,572,558,578,592,566,…,915,801,883,...,945,1043,1107,1179,1222,1273,1318,1362,1393,1434

In [24]:
pd.read_excel('data02.xlsx',skiprows = 2,header = [None])

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,青森,756,813,880,967,985,1180,1283,1383,1427,...,1428,1469,1524,1524,1483,1482,1476,1437,1373,1308
1,岩手,846,901,976,1046,1078,1263,1347,1427,1449,...,1371,1386,1422,1434,1417,1420,1416,1385,1330,1280
2,宮城,962,1044,1143,1235,1247,1567,1663,1727,1743,...,1819,1955,2082,2176,2249,2329,2365,2360,2348,2334
3,秋田,899,936,988,1038,1035,1257,1309,1349,1336,...,1241,1232,1257,1254,1227,1214,1189,1146,1086,1023
4,山形,969,1027,1080,1117,1100,1336,1357,1354,1321,...,1226,1220,1252,1262,1258,1257,1244,1216,1169,1124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,熊本,1233,1296,1354,1387,1338,1766,1828,1896,1856,...,1700,1715,1790,1838,1840,1860,1859,1842,1817,1786
42,大分,860,915,946,980,953,1234,1253,1277,1240,...,1156,1190,1229,1250,1237,1231,1221,1210,1197,1166
43,宮崎,651,691,760,824,823,1026,1091,1139,1135,...,1051,1085,1152,1176,1169,1176,1170,1153,1135,1104
44,鹿児島,1416,1472,1557,1591,1554,1746,1804,2044,1963,...,1729,1724,1785,1819,1798,1794,1786,1753,1706,1648
45,沖縄,572,558,578,592,566,…,915,801,883,...,945,1043,1107,1179,1222,1273,1318,1362,1393,1434

In [25]:
pd.read_excel('data.xlsx',index_col=0)

,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),1965年,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
都道府県,,,,,,,,,,,,,,,,,,,,
全国,55963,59737,64450,69254,71933,78101,84115,90077,94302,99209,104665,111940,117060,121049,123611,125570,126926,127768,128057,127095
北海道,2359,2499,2812,3068,3229,3853,4296,4773,5039,5172,5184,5338,5576,5679,5644,5692,5683,5628,5506,5382
青森,756,813,880,967,985,1180,1283,1383,1427,1417,1428,1469,1524,1524,1483,1482,1476,1437,1373,1308
岩手,846,901,976,1046,1078,1263,1347,1427,1449,1411,1371,1386,1422,1434,1417,1420,1416,1385,1330,1280
宮城,962,1044,1143,1235,1247,1567,1663,1727,1743,1753,1819,1955,2082,2176,2249,2329,2365,2360,2348,2334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
熊本,1233,1296,1354,1387,1338,1766,1828,1896,1856,1771,1700,1715,1790,1838,1840,1860,1859,1842,1817,1786
大分,860,915,946,980,953,1234,1253,1277,1240,1187,1156,1190,1229,1250,1237,1231,1221,1210,1197,1166
宮崎,651,691,760,824,823,1026,1091,1139,1135,1081,1051,1085,1152,1176,1169,1176,1170,1153,1135,1104
鹿児島,1416,1472,1557,1591,1554,1746,1804,2044,1963,1854,1729,1724,1785,1819,1798,1794,1786,1753,1706,1648
沖縄,572,558,578,592,566,…,915,801,883,934,945,1043,1107,1179,1222,1273,1318,1362,1393,1434

In [30]:
pd.read_excel('data.xlsx',index_col='都道府県')#リストの番号でない限り「」で括る必要なし

,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),1965年,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
都道府県,,,,,,,,,,,,,,,,,,,,
全国,55963,59737,64450,69254,71933,78101,84115,90077,94302,99209,104665,111940,117060,121049,123611,125570,126926,127768,128057,127095
北海道,2359,2499,2812,3068,3229,3853,4296,4773,5039,5172,5184,5338,5576,5679,5644,5692,5683,5628,5506,5382
青森,756,813,880,967,985,1180,1283,1383,1427,1417,1428,1469,1524,1524,1483,1482,1476,1437,1373,1308
岩手,846,901,976,1046,1078,1263,1347,1427,1449,1411,1371,1386,1422,1434,1417,1420,1416,1385,1330,1280
宮城,962,1044,1143,1235,1247,1567,1663,1727,1743,1753,1819,1955,2082,2176,2249,2329,2365,2360,2348,2334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
熊本,1233,1296,1354,1387,1338,1766,1828,1896,1856,1771,1700,1715,1790,1838,1840,1860,1859,1842,1817,1786
大分,860,915,946,980,953,1234,1253,1277,1240,1187,1156,1190,1229,1250,1237,1231,1221,1210,1197,1166
宮崎,651,691,760,824,823,1026,1091,1139,1135,1081,1051,1085,1152,1176,1169,1176,1170,1153,1135,1104
鹿児島,1416,1472,1557,1591,1554,1746,1804,2044,1963,1854,1729,1724,1785,1819,1798,1794,1786,1753,1706,1648
沖縄,572,558,578,592,566,…,915,801,883,934,945,1043,1107,1179,1222,1273,1318,1362,1393,1434

In [32]:
df_csv.to_excel('excel.xlsx')

In [33]:
#data.csvをコピーしてから実行、コピーしたデータをそのままデータフレにできる
df_cb = pd.read_clipboard()

In [34]:
df_cb

,都道府県,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),...,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
0,全国,"55,963","59,737","64,450","69,254","71,933","78,101","84,115","90,077","94,302",...,"104,665","111,940","117,060","121,049","123,611","125,570","126,926","127,768","128,057","127,095"
1,北海道,"2,359","2,499","2,812","3,068","3,229","3,853","4,296","4,773","5,039",...,"5,184","5,338","5,576","5,679","5,644","5,692","5,683","5,628","5,506","5,382"
2,青森,756,813,880,967,985,"1,180","1,283","1,383","1,427",...,"1,428","1,469","1,524","1,524","1,483","1,482","1,476","1,437","1,373","1,308"
3,岩手,846,901,976,"1,046","1,078","1,263","1,347","1,427","1,449",...,"1,371","1,386","1,422","1,434","1,417","1,420","1,416","1,385","1,330","1,280"
4,宮城,962,"1,044","1,143","1,235","1,247","1,567","1,663","1,727","1,743",...,"1,819","1,955","2,082","2,176","2,249","2,329","2,365","2,360","2,348","2,334"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,山形,969,"1,027","1,080","1,117","1,100","1,336","1,357","1,354","1,321",...,"1,226","1,220","1,252","1,262","1,258","1,257","1,244","1,216","1,169","1,124"
7,福島,"1,363","1,438","1,508","1,582","1,595","1,992","2,062","2,095","2,051",...,"1,946","1,971","2,035","2,080","2,104","2,134","2,127","2,091","2,029","1,914"
8,茨城,"1,350","1,409","1,487","1,549","1,595","2,014","2,039","2,064","2,047",...,"2,144","2,342","2,558","2,725","2,845","2,956","2,986","2,975","2,970","2,917"
9,栃木,"1,046","1,090","1,142","1,195","1,187","1,534","1,550","1,548","1,514",...,"1,580","1,698","1,792","1,866","1,935","1,984","2,005","2,017","2,008","1,974"
10,群馬,"1,053","1,119","1,186","1,242","1,280","1,573","1,601","1,614","1,578",...,"1,659","1,756","1,849","1,921","1,966","2,004","2,025","2,024","2,008","1,973"

In [35]:
#データベースとの接続について

In [36]:
import sqlite3

In [37]:
df_csv = pd.read_csv('data.csv',encoding='shift-jis')
df_csv

,都道府県,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,1960年3),...,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
0,全国,"55,963","59,737","64,450","69,254","71,933","78,101","84,115","90,077","94,302",...,"104,665","111,940","117,060","121,049","123,611","125,570","126,926","127,768","128,057","127,095"
1,北海道,"2,359","2,499","2,812","3,068","3,229","3,853","4,296","4,773","5,039",...,"5,184","5,338","5,576","5,679","5,644","5,692","5,683","5,628","5,506","5,382"
2,青森,756,813,880,967,985,"1,180","1,283","1,383","1,427",...,"1,428","1,469","1,524","1,524","1,483","1,482","1,476","1,437","1,373","1,308"
3,岩手,846,901,976,"1,046","1,078","1,263","1,347","1,427","1,449",...,"1,371","1,386","1,422","1,434","1,417","1,420","1,416","1,385","1,330","1,280"
4,宮城,962,"1,044","1,143","1,235","1,247","1,567","1,663","1,727","1,743",...,"1,819","1,955","2,082","2,176","2,249","2,329","2,365","2,360","2,348","2,334"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,熊本,"1,233","1,296","1,354","1,387","1,338","1,766","1,828","1,896","1,856",...,"1,700","1,715","1,790","1,838","1,840","1,860","1,859","1,842","1,817","1,786"
44,大分,860,915,946,980,953,"1,234","1,253","1,277","1,240",...,"1,156","1,190","1,229","1,250","1,237","1,231","1,221","1,210","1,197","1,166"
45,宮崎,651,691,760,824,823,"1,026","1,091","1,139","1,135",...,"1,051","1,085","1,152","1,176","1,169","1,176","1,170","1,153","1,135","1,104"
46,鹿児島,"1,416","1,472","1,557","1,591","1,554","1,746","1,804","2,044","1,963",...,"1,729","1,724","1,785","1,819","1,798","1,794","1,786","1,753","1,706","1,648"
47,沖縄,572,558,578,592,566,…,915,801,883,...,945,"1,043","1,107","1,179","1,222","1,273","1,318","1,362","1,393","1,434"

In [41]:
dbname = 'TEST.db'#作成するデータベースの名前
conn = sqlite3.connect(dbname)#コネクションオブジェクトの作成
conn.close()#データベースの切断

In [43]:
conn = sqlite3.connect(dbname)
df_csv.to_sql('test_table',conn,if_exists = 'replace')#if_existsは、同じテーブル名が存在する場合の動作replaceは、テーブルを削除してから新規で作成
conn.close()

In [44]:
#テーブルからデータの取得

In [46]:
conn = sqlite3.connect(dbname)
df_db = pd.read_sql('SELECT * FROM test_table' ,conn)
conn.close()

In [47]:
df_db

,index,都道府県,1920年,1925年,1930年,1935年,1940年1),1947年2),1950年,1955年,...,1970年,1975年,1980年,1985年,1990年,1995年,2000年,2005年,2010年,2015年
0,0,全国,"55,963","59,737","64,450","69,254","71,933","78,101","84,115","90,077",...,"104,665","111,940","117,060","121,049","123,611","125,570","126,926","127,768","128,057","127,095"
1,1,北海道,"2,359","2,499","2,812","3,068","3,229","3,853","4,296","4,773",...,"5,184","5,338","5,576","5,679","5,644","5,692","5,683","5,628","5,506","5,382"
2,2,青森,756,813,880,967,985,"1,180","1,283","1,383",...,"1,428","1,469","1,524","1,524","1,483","1,482","1,476","1,437","1,373","1,308"
3,3,岩手,846,901,976,"1,046","1,078","1,263","1,347","1,427",...,"1,371","1,386","1,422","1,434","1,417","1,420","1,416","1,385","1,330","1,280"
4,4,宮城,962,"1,044","1,143","1,235","1,247","1,567","1,663","1,727",...,"1,819","1,955","2,082","2,176","2,249","2,329","2,365","2,360","2,348","2,334"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,43,熊本,"1,233","1,296","1,354","1,387","1,338","1,766","1,828","1,896",...,"1,700","1,715","1,790","1,838","1,840","1,860","1,859","1,842","1,817","1,786"
44,44,大分,860,915,946,980,953,"1,234","1,253","1,277",...,"1,156","1,190","1,229","1,250","1,237","1,231","1,221","1,210","1,197","1,166"
45,45,宮崎,651,691,760,824,823,"1,026","1,091","1,139",...,"1,051","1,085","1,152","1,176","1,169","1,176","1,170","1,153","1,135","1,104"
46,46,鹿児島,"1,416","1,472","1,557","1,591","1,554","1,746","1,804","2,044",...,"1,729","1,724","1,785","1,819","1,798","1,794","1,786","1,753","1,706","1,648"
47,47,沖縄,572,558,578,592,566,…,915,801,...,945,"1,043","1,107","1,179","1,222","1,273","1,318","1,362","1,393","1,434"

In [48]:
sql = '''
select *
from test_table
where 都道府県　== "東京都"
'''

In [50]:
#確認問題

In [51]:
df_csv = pd.read_csv('data.csv',encoding='shift-jis')

In [53]:
df_csv.to_csv('df_data',encoding='shift-jis')

In [57]:
df_excel = pd.read_excel('data.xlsx')

In [58]:
df_excel.to_excel('df_data.xlsx')